# Generated by Django 5.2.11 on 2026-09-13 19:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0005_alter_companyuser_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="JourneyReport",
            fields=[
                (
                    "report_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("baseline_route_risk", models.FloatField(default=0.0)),
                ("route_risk_score", models.FloatField(default=0.0)),
                ("in_safe_corridor", models.BooleanField(default=True)),
                (
                    "nearest_corridor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("in_high_risk_zone", models.BooleanField(default=False)),
                (
                    "high_risk_zone_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cargo_value_factor",
                    models.FloatField(
                        default=0.0, help_text="Risk contribution from cargo value"
                    ),
                ),
                (
                    "driver_history_factor",
                    models.FloatField(
                        default=0.0,
                        help_text="Risk contribution from driver's past alerts",
                    ),
                ),
                ("composite_risk_score", models.FloatField(default=0.0)),
                ("risk_level", models.CharField(default="LOW", max_length=20)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey_reports",
                        to="surveillance.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
    ]
